version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tasksdb
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: